import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

export enum CategoriaTipo {
  ESPRESSO = 'ESPRESSO',
  AMERICANO = 'AMERICANO',
  CAPPUCCINO = 'CAPPUCCINO',
  LATTE = 'LATTE',
  MOCHA = 'MOCHA',
  FLAT_WHITE = 'FLAT_WHITE',
  MACCHIATO = 'MACCHIATO',
  COLD_BREW = 'COLD_BREW',
  AFFOGATO = 'AFFOGATO',
  TE = 'TE',
  CHOCOLATE_CALIENTE = 'CHOCOLATE_CALIENTE',
  FRAPPE = 'FRAPPE',
  SMOOTHIES = 'SMOOTHIES',
  JUGOS = 'JUGOS',
  PANADERIA = 'PANADERIA',
  PASTELERIA = 'PASTELERIA',
  DESAYUNOS = 'DESAYUNOS',
  GALLETAS = 'GALLETAS',
  TORTAS = 'TORTAS',
  PIZZA = 'PIZZA',
  SUSHI = 'SUSHI',
  HAMBURGUESAS = 'HAMBURGUESAS',
  PASTAS = 'PASTAS',
  COMIDA_MEXICANA = 'COMIDA_MEXICANA',
  COMIDA_CHINA = 'COMIDA_CHINA',
  COMIDA_INDIAN = 'COMIDA_INDIAN',
  COMIDA_PERUANA = 'COMIDA_PERUANA',
  COMIDA_THAI = 'COMIDA_THAI',
  COMIDA_JAPONESA = 'COMIDA_JAPONESA',
  COMIDA_COREANA = 'COMIDA_COREANA',
  COMIDA_MEDITERRANEA = 'COMIDA_MEDITERRANEA',
  COMIDA_ARABE = 'COMIDA_ARABE',
  POSTRES = 'POSTRES',
  SANDWICHES = 'SANDWICHES',
  ENSALADAS = 'ENSALADAS',
  MARISCOS = 'MARISCOS',
  PARRILLAS = 'PARRILLAS',
  SOPAS = 'SOPAS',
  VEGANA = 'VEGANA',
  VEGETARIANA = 'VEGETARIANA',
  ENTRADAS = 'ENTRADAS',
  CERVEZAS = 'CERVEZAS',
  VINOS = 'VINOS',
  COCTELES = 'COCTELES',
  DESTILADOS = 'DESTILADOS',
  BEBIDAS_SIN_ALCOHOL = 'BEBIDAS_SIN_ALCOHOL',
  WHISKY = 'WHISKY',
  RON = 'RON',
  GIN = 'GIN',
  VODKA = 'VODKA',
  TEQUILA = 'TEQUILA',
  MOCKTAILS = 'MOCKTAILS',
  SHOTS = 'SHOTS',
  APERITIVOS = 'APERITIVOS',
  TAPAS = 'TAPAS',
  PICOTEO = 'PICOTEO',
  HOT_DOGS = 'HOT_DOGS',
  TACOS = 'TACOS',
  BURRITOS = 'BURRITOS',
  AREPAS = 'AREPAS',
  EMPANADAS = 'EMPANADAS',
  COMPLETOS = 'COMPLETOS',
  CHORIPAN = 'CHORIPAN',
  QUESADILLAS = 'QUESADILLAS',
  NACHOS = 'NACHOS',
  PAPAS_FRITAS = 'PAPAS_FRITAS',
  WRAPS = 'WRAPS',
  BROCHETAS = 'BROCHETAS',
  HELADOS = 'HELADOS',
  CHURROS = 'CHURROS',
  CREPES = 'CREPES',
  WAFFLES = 'WAFFLES',
  KEBABS = 'KEBABS',
}

@Entity({ name: 'categoria' })
export class Category {
  @PrimaryGeneratedColumn({ type: 'bigint' })
  id!: string;

  @Column({ name: 'tenant_id', type: 'bigint' })
  tenantId!: string;

  @Column({ name: 'nombre', length: 100 })
  name!: string;

  @Column({ name: 'slug', length: 100 })
  slug!: string;

  @Column({
    name: 'tipo_categoria',
    type: 'enum',
    enum: CategoriaTipo,
    enumName: 'categoria_tipo_enum',
  })
  type!: CategoriaTipo;
}
